### ISSUE TITLE
Microphone

### ISSUE THREAD

**Issue by merlindorin** [kpeu3i/gods4#2]
Hi! Really great work! It works perfectly in a sec and the design is nice :)

Do you have any work on micro/speaker?

Just to know, can be useful here (working on a connected car) ;)

**Comment by kpeu3i** [comment]
Hi! Thanks! I'm glad that the library helped you solve your tasks. I also use it to control the robot (GoPiGo). `gods4` does not support a microphone/speaker at the moment. It's not an easy task to add support for these devices. If there is a bit more free time, of course, I will return to this integration.

**Comment by merlindorin** [comment]
@kpeu3i thx for the feedback, I'll be there if you find a way ;)
